In [1]:
import json
import numpy as np
import os
import pandas as pd
import urllib2

In [52]:
url = 'https://poloniex.com/public?command=returnChartData&currencyPair=USDT_BTC&start=1356998100&end=9999999999&period=300'
openUrl = urllib2.urlopen(url)
r = openUrl.read()
openUrl.close()
d = json.loads(r.decode())

In [53]:
df = pd.DataFrame(d)
original_columns=[u'close', u'date', u'high', u'low', u'open']
new_columns = ['Close','Timestamp','High','Low','Open']
df = df.loc[:,original_columns]
df.columns = new_columns
df.head(100)

    Close   Timestamp    High    Low    Open
0   225.0  1424373000    0.33  225.0    0.33
1   225.0  1424373300  225.00  225.0  225.00
2   225.0  1424373600  225.00  225.0  225.00
3   225.0  1424373900  225.00  225.0  225.00
4   225.0  1424374200  225.00  225.0  225.00
5   225.0  1424374500  225.00  225.0  225.00
6   225.0  1424374800  225.00  225.0  225.00
7   225.0  1424375100  225.00  225.0  225.00
8   225.0  1424375400  225.00  225.0  225.00
9   225.0  1424375700  225.00  225.0  225.00
10  225.0  1424376000  225.00  225.0  225.00
11  225.0  1424376300  225.00  225.0  225.00
12  225.0  1424376600  225.00  225.0  225.00
13  225.0  1424376900  225.00  225.0  225.00
14  240.0  1424377200  240.00  225.0  225.00
15  240.0  1424377500  240.00  240.0  240.00
16  240.0  1424377800  240.00  240.0  240.00
17  240.0  1424378100  240.00  240.0  240.00
18  240.0  1424378400  240.00  240.0  240.00
19  244.0  1424378700  244.00  244.0  244.00
20  244.0  1424379000  244.00  244.0  244.00
21  244.0  1424379300  244.00  244.0  244.00
22  244.0  1424379600  244.00  244.0  244.00
23  244.0  1424379900  244.00  244.0  244.00
24  244.0  1424380200  244.00  244.0  244.00
25  244.0  1424380500  244.00  244.0  244.00
26  244.0  1424380800  244.00  244.0  244.00
27  244.0  1424381100  244.00  244.0  244.00
28  244.0  1424381400  244.00  244.0  244.00
29  244.0  1424381700  244.00  244.0  244.00
..    ...         ...     ...    ...     ...
70  244.0  1424394000  244.00  244.0  244.00
71  244.0  1424394300  244.00  244.0  244.00
72  244.0  1424394600  244.00  244.0  244.00
73  244.0  1424394900  244.00  244.0  244.00
74  244.0  1424395200  244.00  244.0  244.00
75  244.0  1424395500  244.00  244.0  244.00
76  244.0  1424395800  244.00  244.0  244.00
77  244.0  1424396100  244.00  244.0  244.00
78  244.0  1424396400  244.00  244.0  244.00
79  244.0  1424396700  244.00  244.0  244.00
80  244.0  1424397000  244.00  244.0  244.00
81  244.0  1424397300  244.00  244.0  244.00
82  244.0  1424397600  244.00  244.0  244.00
83  244.0  1424397900  244.00  244.0  244.00
84  244.0  1424398200  244.00  244.0  244.00
85  244.0  1424398500  244.00  244.0  244.00
86  244.0  1424398800  244.00  244.0  244.00
87  244.0  1424399100  244.00  244.0  244.00
88  244.0  1424399400  244.00  244.0  244.00
89  244.0  1424399700  244.00  244.0  244.00
90  244.0  1424400000  244.00  244.0  244.00
91  244.0  1424400300  244.00  244.0  244.00
92  244.0  1424400600  244.00  244.0  244.00
93  244.0  1424400900  244.00  244.0  244.00
94  244.0  1424401200  244.00  244.0  244.00
95  244.0  1424401500  244.00  244.0  244.00
96  244.0  1424401800  244.00  244.0  244.00
97  244.0  1424402100  244.00  244.0  244.00
98  244.0  1424402400  244.00  244.0  244.00
99  244.0  1424402700  244.00  244.0  244.00

[100 rows x 5 columns]

In [55]:
df.to_csv('data/bitcoin2015to2017.csv',index=None)